[build-system]
requires = ["setuptools >= 77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "is-bot"
license = "Apache-2.0"
description = "Python package to detect bots/crawlers/spiders via user-agent"
readme = "README.md"
authors = [{ name = "Roman Snegirev", email = "snegiryev@gmail.com" }]
keywords = [
    "python",
    "bots",
    "crawlers",
    "web-crawlers",
    "user-agent",
    "user-agent-parser",
]
requires-python = ">=3.9.0"
dynamic = ["version"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: MacOS",
    "Operating System :: Microsoft",
    "Operating System :: POSIX :: Linux",
    "Topic :: Internet :: WWW/HTTP",
    "Intended Audience :: Developers",
]

dependencies = ["regex>=2022.8.17"]

[dependency-groups]
dev = ["mypy", "ruff", "pytest", "pytest-cov"]

[project.urls]
homepage = "https://github.com/romis2012/is-bot"
repository = "https://github.com/romis2012/is-bot"

[tool.setuptools.dynamic]
version = { attr = "is_bot.__version__" }

[tool.setuptools.packages.find]
include = ["is_bot*"]

[tool.mypy]
allow_redefinition = true
disable_error_code = ["import-untyped", "no-redef"]

[tool.ruff]
line-length = 89
indent-width = 4

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",
    "CPY001", # missing-copyright-notice (CPY001)
    "FA100",  # future-rewritable-type-annotation (FA100)
    "S101",   # assert (S101)
    "COM812", # missing-trailing-comma (COM812)
    "TC003", # typing-only-standard-library-import (TC003)
]
